let grocery = {
    "start": "$phrase",
  
    "phrase": [
      "$1.99 Only",
      "No Bargain",
      "Sweet mangoes, sour mangoes!",
      "Buy 1, get 1 free",
      "Only here",
      "$5.99 Only",
      "Come on, come on, everything is available!",
      "Best price in town",
      "Spicy enough",
      "Cheap goods, good goods!",
      "$0.99 Only",
      "Cheap!",
      "Take a look at least!",
      "Smile for a discount",
      "$7.99 Only",
      "No returns, only memories",
      "Freshly picked today",
      "Fresher than your in-laws",
      "Price drops tomorrow",
      "Buy now, thank me later",
      "$4.99 for 5",
      "$3.99 Only",
      "Hurry!",
      "Mom approved freshness",
      "Best deal, no questions",
      "Wallet-friendly prices",
      "Find it anywhere else?",
      "Buy Now!",
      "Low price, practically free",
      "Get it while it's hot",
      "Throw in a secret, get more",
      "Fresh, even veggies gossip",
      "No questions, just buy",
      "Buy 1, get chai free",
    ]
  };